### PR TITLE
Run user code in same process as the request

### PR DESCRIPTION
**Pull request by tipabu**
This has a couple advantages:

- No need for temporary files
- More control over what globals and builtins are available

### What is this PR?
Please make yourself a check.
- [ ] Adding new stage or lesson
  - [ ] Have you read [CONTRIBUTING.md](https://github.com/YunOSC/PyFun-Backend/blob/master/.github/CONTRIBUTING.md) yet?
  - [ ] Have you pick a topic?
  - [ ] Are there any unit test has been prepared?
- [ ] Feature
- [X] Refactor

### CODE REVIEW

**Comment by tipabu** [comment]
Ah, got it. Good, actually -- I was dreading trying to figure out how to prevent `import` statements, and [I think the rabbit hole only goes deeper](https://stackoverflow.com/questions/35804961/python-eval-is-it-still-dangerous-if-i-disable-builtins-and-attribute-access) when trying to eval user code 🙂

I'll drop an empty dict in for the globals, which will still provide the expected built-ins, and remove the sneaky-input unit test.

**Comment by tipabu** [comment]
Good catch. Done.

**Comment by jackey8616** [comment]
Oops, forgot `contest.py`
[Line 10 to 16](https://github.com/YunOSC/PyFun-Backend/blob/master/tests/conftest.py#L10,L16) and [Line 6](https://github.com/YunOSC/PyFun-Backend/blob/master/tests/conftest.py#L6)

**Comment by jackey8616** [comment]
Good work! Thanks a lot!

**Pull request merged**
