### PR TITLE
Adds List Comprehensions to Stage 2

### PR DESCRIPTION
**Pull request by joshhacksthings**
Addresses #12 by adding list comprehension lesson. May want to consider a lesson teaching `range()` before this, though. Will add if I have time.

### CODE REVIEW

**Comment by jackey8616** [comment]
@joshhacksthings  please squash all commits into one, and provide some commit's body message.
Thx and nice work!

**Comment by joshhacksthings** [comment]
@jackey8616 , just squashed, lmk if I did that correctly!

**Comment by jackey8616** [comment]
@joshhacksthings  You need to locally squash your commit and force push to your repo.
Thx. :smiley:

**Comment by joshhacksthings** [comment]
@jackey8616 Cool! I learned something new today! Thanks!

**Comment by jackey8616** [comment]
@joshhacksthings  Don't forget https://github.com/YunOSC/PyFun-Backend/pull/16/commits/59cbc6a49e9df6ec73700dee2a49a352dd1adc5c
:smile:

**Comment by jackey8616** [comment]
@joshhacksthings 
The test code have massively changed.
Please check our CONTRIBUTING.md again.
Sorry for that. 😢
Also, do forgot re-index file name.

**Comment by joshhacksthings** [comment]
@jackey8616 lmk how that looks

**Comment by jackey8616** [comment]
@joshhacksthings 
It's looks good to go!
Thx and nice job!

**Pull request merged**
