### PR TITLE
Added While loop and List data structure in stage one

### PR DESCRIPTION
**Pull request by rozig**
Contribution for #1 . @jackey8616 can you review the code? I just want to make sure its correct or not.

### CODE REVIEW

**Comment by jackey8616** [comment]
It is all correct! Excellent work!
btw, I think s7_list.py is a little bit hard for newbie,
and sort two times seem unnecessary.

But NICE WORK! :smile: :smile: :smile: 

If your work is done, Just let me know to accept your PR.

**Comment by rozig** [comment]
On s7_list.py, idea is to use `sort()` function first and then use `reverse()`. Just wanted to let newbies know that there is a built-in function for reverse a list.

**Comment by jackey8616** [comment]
I got it.
Maybe you can put a `print` b/w two sort to let them understand shows what happen in stdout during two build-in function get called.

**Comment by rozig** [comment]
That is also a good idea. But I can't understand why you are thinking that I'm sorting two times.

**Comment by jackey8616** [comment]
First time i use `list.sort()`
and second time `list.sort(reverse=True)` comes to my mind.
:laughing:

**Comment by rozig** [comment]
Thats why I added the built-in function reference and 2 empty fields.
First`list.sort()` and then `list.reverse()`.

**Comment by jackey8616** [comment]
Maybe list_._____() ?

**Comment by rozig** [comment]
You can accept this PR. I will create new one with more specific description and will add Python data structures and its usage.

**Comment by jackey8616** [comment]
@rozig Can you squash two commit and give some commit body massage into it?
Appreciate! :smiley:

**Comment by jackey8616** [comment]
@rozig  I made some changes like reduce duplicate code in [lesson].py,
And also provide a test to let contributors to check whether there lesson design have problems or not.
Maybe you can check the [Contributing.md](https://github.com/YunOSC/PyFun-Backend/blob/master/CONTRIBUTING.md) again to get latest info.

After your work is down. We can re-consider about merge this PR.
Thx a lot. 😃 😃

**Comment by rozig** [comment]
I fixed the code according to changes and I created tests for them. One more thing, I think we should keep PEP8 style guide in our code. What do you think?

**Comment by jackey8616** [comment]
PEP8, what a coincidence! I'm also think about this!
That's a brilliant idea.
But let me squash and merge this PR first.

PEP8 I will open a new issue for anyone who want to try!
Thx for this PR! Really appreciate it!

**Comment by rozig** [comment]
If you open new issue for PEP8, you can assign it to me.

**Pull request merged**
